apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: markvinton/frontend:1.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: VITE_API_BASE_URL
            value: "a82114e23bc584941b0c9dd36ca3cab5-483656580.eu-west-2.elb.amazonaws.com"
