apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: public.ecr.aws/m0z9x0c0/team-ecr-repository-frontend:1.0.5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: VITE_API_BASE_URL
            value: "adc5ea691884845899e16b79143f7926-130469647.eu-west-2.elb.amazonaws.com:8080"
          - name: DATABASE_USER
            value: "rymp_username"
          - name: DATABASE_PASS
            value: "rymp_password"
          - name: DATABASE_HOST
            value: "dbinstance.ctu6yyemsckt.eu-west-2.rds.amazonaws.com"
          - name: DATABASE_NAME
            value: "dbinstance"  
